enableGlobalCache: true
nodeLinker: pnp
compressionLevel: 9
enableHardenedMode: false
nmMode: hardlinks-local
enableImmutableCache: false
enableInlineHunks: true
enableInlineBuilds: true
nmHoistingLimits: workspaces
pnpEnableEsmLoader: true
pnpMode: strict
pnpFallbackMode: dependencies-only
